# Generated by Django 3.1.13 on 2021-10-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0003_auto_20211029_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientslist',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_ingredients', to='ingredients.ingredient', unique=True),
        ),
    ]
