# Generated by Django 3.1.13 on 2021-10-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0004_auto_20211031_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientslist',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_ingredients', to='ingredients.ingredient'),
        ),
    ]
