version: '3.3'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
      
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static_django/
      - media_value:/var/html/media/
    depends_on:
      - web
    networks: 
      - foodgram_network

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/envfiles/.env.prod
    networks: 
      - foodgram_network
    depends_on:
      - frontend

  web:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../backend:/usr/src/app/web
      - ../data:/usr/src/app/data
      - static_value:/usr/src/app/web/static_django/
      - media_value:/usr/src/app/web/media/
    env_file:
      - ../backend/envfiles/.env.prod
    depends_on:
      - db
    networks: 
      - foodgram_network

networks:
  foodgram_network:
    driver: bridge

volumes:
  postgres_data:
  static_value:
  media_value: