name: Stzrt project

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: ${{ secrets.SQL_HOST }}
      SQL_PORT: ${{ secrets.SQL_PORT }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install pipenv
          cd backend
          pipenv install --system --deploy --dev
      - name: Test with flake8 (django tests and pytest )
        # обязательно появятся в версии 2.0
        # python manage.py test
        # pytest
        run: |
          python -m flake8
         
  build_and_push_to_docker_hub:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push backend_foodgram
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend_foodgram:latest
      - name: build and push frontend_foodgram
        uses: docker/build-push-action@v2
        with:
          context: frontend
          file: Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend_foodgram:latest
