name: Stzrt project

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: ${{ secrets.SQL_HOST }}
      SQL_PORT: ${{ secrets.SQL_PORT }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install pipenv
          cd /backend
          pipenv install --system --deploy --dev
      - name: Test with flake8 (django tests and pytest )
        # обязательно появятся в версии 2.0
        # python manage.py test
        # pytest
        run: |
          python -m flake8
         
